services:
  postgres:
    image: postgres:16
    container_name: bankapp-postgres
    environment:
      POSTGRES_DB: bankapp
      POSTGRES_USER: bankapp
      POSTGRES_PASSWORD: bankapp
    ports:
      - "5432:5432"
    volumes:
      - bankapp_pgdata:/var/lib/postgresql/data

volumes:
  bankapp_pgdata:
